// src/app/layout.tsx
import "./globals.css"; // 전역 스타일
import type { Metadata } from "next"; // Next.js 메타데이터 타입
import { Inter } from "next/font/google"; // 구글 폰트 로더
import Link from "next/link"; // 클라이언트 라우팅
import dataTexts from "./data/dataText"; // 네비/푸터에 쓰일 텍스트 데이터
import { PostProvider } from "./context/PostContext"; // ✅ 전역 데이터 공급자(Provider)

// (선택) 부트스트랩 CSS를 전역에서 한 번만 쓰고 싶다면 여기서 import해도 됩니다.
// import "bootstrap/dist/css/bootstrap.min.css";

interface DataText {
  main: string;
  subCaps1: string;
  sub1: string;
  subCaps2: string;
  sub2: string;
  subCaps3: string;
  sub3: string;
  footer: string;
}

// 구글 폰트 설정(Inter)
const inter = Inter({ subsets: ["latin"] });

// 페이지 공통 메타데이터
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 모든 페이지의 공통 레이아웃
export default function RootLayout({
  children, // 각 페이지가 여기에 렌더링된다.
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 전역 폰트 클래스 적용 */}
      <body className={inter.className}>
        {/* 공통 네비게이션 */}
        <Nav />

        {/* ✅ 여기서 전역 데이터(Context)를 공급한다.
            - PostProvider로 children 전체(모든 페이지)를 감싸면
              어느 페이지에서든 usePosts()로 posts, loading, error를 가져올 수 있다. */}
        <PostProvider>{children}</PostProvider>

        {/* 공통 푸터 */}
        <Footer />
      </body>
    </html>
  );
}

// 상단 네비게이션 컴포넌트
function Nav() {
  return (
    <nav className="navbar navbar-expand-lg bg-body-tertiary m-3">
      <div className="container-fluid">
        {/* 홈으로 이동하는 브랜드 링크 + 로고 */}
        <Link href="/" className="navbar-brand">
          {/* (개선 여지) next/image 사용을 권장 */}
          <h3>NextaGram</h3>
        </Link>

        {/* 모바일 토글 버튼 */}
        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        {/* 접히는 네비게이션 메뉴 */}
        <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div className="navbar-nav">
            {/* dataTexts를 이용해 URL/레이블을 데이터바인딩 */}
            <Link href={`/${dataTexts[0].sub1}`} className="nav-link">
              {dataTexts[0].subCaps1}
            </Link>
            <Link href={`/${dataTexts[0].sub2}`} className="nav-link">
              {dataTexts[0].subCaps2}
            </Link>
            <Link href={`/${dataTexts[0].sub3}`} className="nav-link">
              {dataTexts[0].subCaps3}
            </Link>
          </div>
        </div>
      </div>
    </nav>
  );
}

// 하단 푸터 컴포넌트
function Footer() {
  return (
    <div className="card m-3">
      <div className="card-header">Image Copyright</div>
      <div className="card-body">
        {/* dataTexts에 있는 footer 텍스트 바인딩 */}
        <h5 className="card-title">{dataTexts[0].footer}</h5>
        <p className="card-text">
          With supporting text below as a natural lead-in to additional content.
        </p>
        <a
          href="https://unsplash.com/"
          className="btn btn-outline-secondary fs-6"
        >
          Go {dataTexts[0].footer}
        </a>
      </div>
    </div>
  );
}
